async function call(path, options = {}) {
  const response = await fetch(`/api${path}`, {
    ...options,
    headers: { 'content-type': 'application/json', ...options.headers },
  });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error?.message ?? 'Erreur interne.');
  return body;
}

export const api = {
  activatePrompt: (id, versionId) => call(`/prompts/${id}/activate`, { method: 'POST', body: JSON.stringify({ versionId }) }),
  activateContract: (id, versionId) => call(`/contracts/${id}/activate`, { method: 'POST', body: JSON.stringify({ versionId }) }),
  activateCliProfile: (id, versionId) => call(`/cli-profiles/${id}/activate`, { method: 'POST', body: JSON.stringify({ versionId }) }),
  artifacts: runId => call(`/runs/${runId}/artifacts`),
  createIntake: profile => call('/intake/dossiers', { method: 'POST', body: JSON.stringify(profile) }),
  createPromptVersion: (id, expectedDraftHash) => call(`/prompts/${id}/versions`, { method: 'POST', body: JSON.stringify({ expectedDraftHash }) }),
  createContractVersion: (id, expectedDraftHash) => call(`/contracts/${id}/versions`, { method: 'POST', body: JSON.stringify({ expectedDraftHash }) }),
  createCliProfileVersion: (id, expectedDraftHash) => call(`/cli-profiles/${id}/versions`, { method: 'POST', body: JSON.stringify({ expectedDraftHash }) }),
  createWorkflowVersion: (id, expectedDraftHash) => call(`/workflows/${id}/versions`, { method: 'POST', body: JSON.stringify({ expectedDraftHash }) }),
  decideRun: (id, decision) => call(`/runs/${id}/decision`, { method: 'PUT', body: JSON.stringify({ decision }) }),
  deleteSecret: id => call(`/providers/${id}/secret`, { method: 'DELETE' }),
  dossier: id => call(`/dossiers/${id}`),
  dossiers: () => call('/dossiers'),
  getPrompt: id => call(`/prompts/${id}`),
  getContract: id => call(`/contracts/${id}`),
  getCliProfile: id => call(`/cli-profiles/${id}`),
  getWorkflow: id => call(`/workflows/${id}`),
  internetSearch: query => call('/internet/search', { method: 'POST', body: JSON.stringify({ query }) }),
  openWorkflowResource: (workflowId, payload) => call(`/workflows/${workflowId}/resources/open`, { method: 'POST', body: JSON.stringify(payload) }),
  openDossier: id => call(`/dossiers/${id}/open`, { method: 'POST' }),
  prompts: () => call('/prompts'),
  contracts: () => call('/contracts'),
  cliProfiles: () => call('/cli-profiles'),
  providers: () => call('/providers'),
  publicDemoRequests: () => call('/public/demo-requests'),
  publicRequests: () => call('/public/requests'),
  publicDecision: (id, decision) => call(`/public/demo-requests/${id}/decision`, { method: 'POST', body: JSON.stringify({ decision }) }),
  providerModels: id => call(`/providers/${id}/models`),
  resumeRun: id => call(`/runs/${id}/resume`, { method: 'POST' }),
  run: id => call(`/runs/${id}`),
  events: id => call(`/runs/${id}/events`),
  runs: () => call('/runs'),
  savePrompt: (id, markdown, expectedHash) => call(`/prompts/${id}/draft`, { method: 'PUT', body: JSON.stringify({ markdown, expectedHash }) }),
  saveContract: (id, payload, expectedHash) => call(`/contracts/${id}/draft`, { method: 'PUT', body: JSON.stringify({ ...payload, expectedHash }) }),
  saveCliProfile: (id, payload, expectedHash) => call(`/cli-profiles/${id}/draft`, { method: 'PUT', body: JSON.stringify({ ...payload, expectedHash }) }),
  saveWorkflow: (id, definition, expectedHash) => call(`/workflows/${id}/draft`, { method: 'PUT', body: JSON.stringify({ definition, expectedHash }) }),
  saveSecret: (id, secret) => call(`/providers/${id}/secret`, { method: 'PUT', body: JSON.stringify({ secret }) }),
  setEnabled: (id, enabled) => call(`/providers/${id}/enabled`, { method: 'PUT', body: JSON.stringify({ enabled }) }),
  startDossierRun: (id, fault = null) => call(`/dossiers/${id}/runs`, { method: 'POST', body: JSON.stringify({ fault }) }),
  startRun: (workflowId, input) => call('/runs', { method: 'POST', body: JSON.stringify({ workflowId, input }) }),
  startSimulation: (profile, fault = null) => call('/simulations/client-site', { method: 'POST', body: JSON.stringify({ profile, fault }) }),
  testProvider: id => call(`/providers/${id}/test`, { method: 'POST' }),
  testProviderSecret: (id, secret) => call(`/providers/${id}/test-secret`, { method: 'POST', body: JSON.stringify({ secret }) }),
  activateWorkflow: (id, versionId) => call(`/workflows/${id}/activate`, { method: 'POST', body: JSON.stringify({ versionId }) }),
  activateTemplate: (id, versionId) => call(`/templates/${id}/activate`, { method: 'POST', body: JSON.stringify({ versionId }) }),
  createTemplateVersion: (id, expectedDraftHash) => call(`/templates/${id}/versions`, { method: 'POST', body: JSON.stringify({ expectedDraftHash }) }),
  deleteTemplate: id => call(`/templates/${id}`, { method: 'DELETE' }),
  getTemplate: id => call(`/templates/${id}`),
  saveTemplate: (id, payload, expectedHash) => call(`/templates/${id}/draft`, { method: 'PUT', body: JSON.stringify({ ...payload, expectedHash }) }),
  templates: () => call('/templates'),
  workflows: () => call('/workflows'),
};
