import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve('.');
test('cockpit utilise l’API et une iconographie SVG cohérente', async () => {
  const [html, intake, app, api, demo, icons] = await Promise.all([readFile(path.join(root, 'app/index.html'), 'utf8'), readFile(path.join(root, 'app/intake.html'), 'utf8'), readFile(path.join(root, 'app/app.mjs'), 'utf8'), readFile(path.join(root, 'app/api.mjs'), 'utf8'), readFile(path.join(root, 'app/demo.mjs'), 'utf8'), readFile(path.join(root, 'app/icons.mjs'), 'utf8')]);
  assert.match(html, /id="app"/); assert.doesNotMatch(html, /brand-mark/); assert.match(intake, /assets\/brand-rock\.png/); assert.match(app, /data-configuration-tab="prompts"/); assert.match(app, /data-configuration-tab="contracts"/); assert.match(app, /data-configuration-tab="cli"/); assert.match(app, /Contrat de sortie/); assert.match(app, /Profils CLI/); assert.match(api, /\/contracts/); assert.match(api, /\/cli-profiles/); assert.doesNotMatch(app, /badge\(item\.activeVersionId/); assert.doesNotMatch(app, /restaurant pattaya/); assert.doesNotMatch(app, /Aucun registrar actif/); assert.match(app, /placeholder="Nom de domaine"/); assert.equal(api.includes('fetch(`/api'), true); assert.doesNotMatch(app, /onclick=/); assert.doesNotMatch(`${html}${intake}${app}${api}${icons}`, /Mistral/); assert.match(icons, /viewBox="0 0 20 20"/);
  assert.match(app, /function rememberConfigurationDraft\(source, read\)/); assert.match(app, /input\.addEventListener\('pointerdown', event => event\.stopPropagation\(\)\)/); assert.match(app, /input\.addEventListener\('click', event => event\.stopPropagation\(\)\)/); assert.match(app, /input\.addEventListener\('input', sync\)/); assert.match(app, /input\.addEventListener\('change', sync\)/); assert.match(app, /rememberConfigurationDraft\(source, readWorkflowForm\)/); assert.match(app, /rememberConfigurationDraft\(source, readPrompt\)/); assert.match(app, /rememberConfigurationDraft\(source, readContract\)/); assert.match(app, /rememberConfigurationDraft\(source, readCliProfile\)/); assert.match(app, /state\.configurationDraft = \{ \.\.\.source, \.\.\.draft \}/); assert.match(app, /data-step-provider/); assert.match(app, /api\.providerModels\(providerId\)/); assert.doesNotMatch(app, /<input type="number"/); assert.match(app, /inputmode="decimal"/);
  assert.match(app, /class="workflow-editor-step/); assert.match(app, /class="step-main"/); assert.match(app, /data-open-workflow-resource/); assert.match(app, /api\.openWorkflowResource/); assert.match(app, /querySelectorAll\('\[data-workflow-step\] \.step-main'\)/); assert.doesNotMatch(app, /detail\.onclick = event/); assert.doesNotMatch(app, /data-open-step-field/); assert.doesNotMatch(app, /step\.implementation \? ` ·/); assert.match(app, /const hasAiFields = step\.kind === 'ai'/); assert.match(app, /data-step-field="outputTemplateId"/); assert.match(app, /api\.publicDemoRequests/); assert.match(app, /api\.publicDecision/); assert.doesNotMatch(demo, /decision.*APPROVED/);
});
